stages:
  - build
  - test
  - docker
  - deploy

variables:
  REGISTRY: registry.gitlab.com/jala-university1/cohort-3/es.co.cssd-352.ga.t1.26.m2/sa/syntaxerror2/pix-pro/client/client

# STAGE: build (Install dependencies and compile Angular)
build:angular:
  stage: build
  image: node:22-alpine
  cache:
    key: npm-$CI_COMMIT_REF_SLUG
    paths:
      - pixpro-frontend/node_modules/
  script:
    - cd pixpro-frontend
    - npm ci
    - mkdir -p src/environments
    - |
      cat > src/environments/environment.production.ts << EOF
      export const environment = {
        production: true,
        apiUrl: '${API_URL}'
      };
      EOF
    - |
      cat > src/environments/environment.ts << EOF
      export const environment = {
        production: false,
        apiUrl: '${API_URL}'
      };
      EOF
    - npm run build -- --configuration production
  artifacts:
    paths:
      - pixpro-frontend/dist/
    expire_in: 1 hour

# STAGE: test (unit testing)
test:unit:
  stage: test
  image: node:22-alpine
  allow_failure: true
  cache:
    key: npm-$CI_COMMIT_REF_SLUG
    paths:
      - pixpro-frontend/node_modules/
  script:
    - cd pixpro-frontend
    - npm ci
    - mkdir -p src/environments
    - |
      cat > src/environments/environment.ts << EOF
      export const environment = {
        production: false,
        apiUrl: '${API_URL}'
      };
      EOF
    - npm run test -- --watch=false
  allow_failure: true

docker:build-push:
  stage: docker
  image: docker:27
  services:
    - docker:27-dind
  dependencies:
    - build:angular
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build
        -t $REGISTRY:$CI_COMMIT_SHA
        -t $REGISTRY:latest
        .
    - docker push $REGISTRY:$CI_COMMIT_SHA
    - docker push $REGISTRY:latest

# STAGE: deploy (It only runs when there's a push to main. It connects to the Manager via SSH and updates the frontend service in the Swarm cluster.)
deploy:swarm:
  stage: deploy
  image: alpine:3.19
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  before_script:
    - apk add --no-cache openssh-client
    - eval $(ssh-agent -s)
    - echo "$SWARM_MANAGER_SSH_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh && chmod 700 ~/.ssh
    - ssh-keyscan $SWARM_MANAGER_IP >> ~/.ssh/known_hosts
  script:
    - ssh deploy@$SWARM_MANAGER_IP "
        docker service update
          --image $REGISTRY:$CI_COMMIT_SHA
          --update-parallelism 1
          --update-delay 10s
          --update-failure-action rollback
          --update-order start-first
          pixpro_frontend
      "
